package com.rxcorp.bdf.datalake.dk9.ndh.loadAsset.model.ods.logical

final case class NdhOdsError(err_typ_nm: String,
                             err_cd: String,
                             err_desc: String,
                             err_clmn_nm: String,
                             err_clmn_val: String,
                             supld_pcmdty_id: String,
                             dervd_pd_pd_id: String,
                             dervd_sum_pd_lvl_cd: String,
                             supld_ctry_nm: String,
                             supld_region_bndry_cd: String,
                             supld_super_brick_bndry_cd: String,
                             supld_brick_bndry_cd: String,
                             dervd_pcmdty_lvl_cd: String,
                             bus_eff_dt: String,
                             bus_expry_dt: String,
                             publ_eff_ts: String,
                             proc_eff_ts: String,
                             proc_expry_ts: String,
                             oprtnl_stat_cd: String,
                             btch_id: String,
                             file_id: String,
                             opr_supld_pd_id: String)