package com.rxcorp.bdf.datalake.dk9.ndh.loadAsset.model.dwh.physical.shared

import com.rxcorp.bdf.datalake.dk9.ndh.loadAsset.common.AppContext
import com.rxcorp.bdf.datalake.dk9.ndh.loadAsset.common.model.PartitionTable
import org.apache.spark.sql.types._

abstract class AbstractDspnsdRxTrans(appContext: AppContext) extends PartitionTable("") {

  override lazy val logicalName: String = "Dispensed Prescription Transaction"
  override lazy val physicalName: String = "dspnsd_rx_trans"

  override lazy val tableColumns = Array(
      ("dspnsd_rx_trans_id", "STRING")
    , ("bus_eff_dt", "TIMESTAMP")
    , ("bus_expry_dt", "TIMESTAMP")
    , ("proc_eff_ts", "TIMESTAMP")
    , ("proc_expry_ts", "TIMESTAMP")
    , ("panel_mbr_cd", "STRING")
    , ("dspnsing_oac_id", "STRING")
    , ("dspnsing_oac_lgcy_id", "BIGINT")
    , ("dspnsd_fcc_id", "BIGINT")
    , ("pscr_fcc_id", "BIGINT")
    , ("dspnsing_sys_rec_typ_cd", "STRING")
    , ("rx_typ_cd", "STRING")
    , ("rx_fill_st_cd", "TINYINT")
    , ("dspnsing_chnl_typ_cd", "STRING")
    , ("late_rec_ind", "TINYINT")
    , ("rptbl_rec_ind", "TINYINT")
    , ("rptbl_rec_typ_cd", "TINYINT")
    , ("dspnsd_qty", "DECIMAL(38,4)")
    , ("pscr_qty", "DECIMAL(38,4)")
    , ("sllr_expc_pay_amt", "DECIMAL(38,2)")
    , ("nrmlz_rx_dspnsd_dt", "TIMESTAMP")
    , ("nrmlz_dspnsd_pcmdty_desc", "STRING")
    , ("nrmlz_pscr_pcmdty_desc", "STRING")
    , ("supld_file_cre_dt", "INT")
    , ("supld_file_id", "STRING")
    , ("cff_data_strc_def_nm", "STRING")
    , ("supld_data_strc_def_nm", "STRING")
    , ("supld_dspnsing_oac_id", "STRING")
    , ("supld_dspnsing_oac_nm", "STRING")
    , ("supld_dspnsing_oac_addr_txt", "STRING")
    , ("supld_dspnsing_oac_pstl_cd_cd", "STRING")
    , ("supld_dspnsd_rx_grp_id", "STRING")
    , ("supld_dspnsd_rx_item_seq_nbr", "INT")
    , ("supld_rx_dspnsd_dt", "INT")
    , ("supld_rx_dspnsd_tm", "INT")
    , ("supld_pscrng_medpro_encrypt_id", "STRING")
    , ("supld_dspnsing_sys_rec_typ_cd", "STRING")
    , ("supld_dspnsd_rx_collected_ind", "STRING")
    , ("supld_dspnsd_rx_pat_instr_txt", "STRING")
    , ("supld_part_fill_rmng_unit_qty", "STRING")
    , ("supld_nrsg_hm_ind", "STRING")
    , ("supld_med_diag_cd_list_txt", "STRING")
    , ("supld_reimbmnt_catg_cd", "STRING")
    , ("supld_rx_typ_cd", "STRING")
    , ("supld_rx_fill_typ_cd", "INT")
    , ("supld_rx_fill_st_cd", "STRING")
    , ("supld_dspnsd_qty", "STRING")
    , ("supld_pscr_qty", "STRING")
    , ("supld_dspnsd_rx_item_uom_cd", "STRING")
    , ("supld_dspnsd_rx_item_uom_txt", "STRING")
    , ("supld_dspnsd_pip_id", "STRING")
    , ("supld_pscr_pip_id", "STRING")
    , ("supld_dspnsd_dmd_id", "STRING")
    , ("supld_pscr_dmd_id", "STRING")
    , ("supld_dspnsd_pmr1_id", "STRING")
    , ("supld_pscr_pmr1_id", "STRING")
    , ("supld_dspnsd_pmr2_id", "STRING")
    , ("supld_pscr_pmr2_id", "STRING")
    , ("supld_dspnsd_othr1_extrnl_id", "STRING")
    , ("supld_pscr_othr1_extrnl_id", "STRING")
    , ("supld_dspnsd_othr2_extrnl_id", "STRING")
    , ("supld_pscr_othr2_extrnl_id", "STRING")
    , ("supld_dspnsd_pcmdty_desc", "STRING")
    , ("supld_pscr_pcmdty_desc", "STRING")
    , ("supld_dspnsd_cmdty_prof_qty", "STRING")
    , ("supld_pscr_cmdty_prof_qty", "STRING")
    , ("supld_dspnsd_cmdty_strnt_txt", "STRING")
    , ("supld_pscr_cmdty_strnt_txt", "STRING")
    , ("supld_dspnsd_generic_pcmdty_ind", "INT")
    , ("supld_pscr_generic_pcmdty_ind", "STRING")
    , ("supld_dspnsd_ean13_id", "STRING")
    , ("supld_sllr_expc_pay_amt", "STRING")
    , ("publ_eff_ts", "TIMESTAMP")
    , ("proc_nm", "STRING")
    , ("src_sys_cre_ts", "TIMESTAMP")
    , ("src_sys_cre_by_nm", "STRING")
    , ("src_sys_updt_ts", "TIMESTAMP")
    , ("src_sys_updt_by_nm", "STRING")
    , ("src_sys_id", "STRING")
    , ("src_sys_impl_id", "STRING")
    , ("src_sys_oprtnl_stat_cd", "STRING")
    , ("src_sys_oprtnl_stat_ts", "TIMESTAMP")
    , ("src_sys_btch_id", "STRING")
    , ("oprtnl_stat_cd", "TINYINT")
    , ("btch_id", "STRING")
    , ("cre_by_nm", "STRING")
    , ("cre_ts", "TIMESTAMP")
    , ("trans_orig_typ_cd", "TINYINT")
    , ("trans_correct_id", "STRING")
    , ("origl_trans_id", "STRING")
    , ("dspnsing_oac_ref_impl_id", "STRING")
    , ("dspnsing_oac_lgcy_ref_impl_id", "STRING")
    , ("dspnsing_oac_brdgg_proc_ts", "STRING")
    , ("dspnsing_oac_brdgg_accrcy_pct", "DECIMAL(5,2)")
    , ("dspnsing_oac_brdgg_meth_nm", "STRING")
    , ("dspnsing_oac_brdgg_stat_cd", "STRING")
    , ("dspnsd_fcc_ref_impl_id", "STRING")
    , ("dspnsd_fcc_brdgg_proc_ts", "STRING")
    , ("dspnsd_fcc_brdgg_accrcy_pct", "DECIMAL(5,2)")
    , ("dspnsd_fcc_brdgg_meth_nm", "STRING")
    , ("dspnsd_fcc_brdgg_stat_cd", "STRING")
    , ("pscr_fcc_ref_impl_id", "STRING")
    , ("pscr_fcc_brdgg_proc_ts", "STRING")
    , ("pscr_fcc_brdgg_accrcy_pct", "DECIMAL(5,2)")
    , ("pscr_fcc_brdgg_meth_nm", "STRING")
    , ("pscr_fcc_brdgg_stat_cd", "STRING")
  )

  override lazy val partitionColumns = Array(
      ("rx_dspnsd_tm_pd_id", "INT")
    , ("dervd_dsupp_proc_id", "STRING")
   )

  override lazy val schema = (new StructType)
    .add("dspnsd_rx_trans_id", StringType)
    .add("bus_eff_dt", TimestampType)
    .add("bus_expry_dt", TimestampType)
    .add("proc_eff_ts", TimestampType)
    .add("proc_expry_ts", TimestampType)
    .add("panel_mbr_cd", StringType)
    .add("dspnsing_oac_id", StringType)
    .add("dspnsing_oac_lgcy_id", LongType)
    .add("dspnsd_fcc_id", LongType)
    .add("pscr_fcc_id", LongType)
    .add("dspnsing_sys_rec_typ_cd", StringType)
    .add("rx_typ_cd", StringType)
    .add("rx_fill_st_cd", ShortType)
    .add("dspnsing_chnl_typ_cd", StringType)
    .add("late_rec_ind", ShortType)
    .add("rptbl_rec_ind", ShortType)
    .add("rptbl_rec_typ_cd", ShortType)
    .add("dspnsd_qty", DecimalType(38,4))
    .add("pscr_qty", DecimalType(38,4))
    .add("sllr_expc_pay_amt", DecimalType(38,2))
    .add("nrmlz_rx_dspnsd_dt", TimestampType)
    .add("nrmlz_dspnsd_pcmdty_desc", StringType)
    .add("nrmlz_pscr_pcmdty_desc", StringType)
    .add("supld_file_cre_dt", IntegerType)
    .add("supld_file_id", StringType)
    .add("cff_data_strc_def_nm", StringType)
    .add("supld_data_strc_def_nm", StringType)
    .add("supld_dspnsing_oac_id", StringType)
    .add("supld_dspnsing_oac_nm", StringType)
    .add("supld_dspnsing_oac_addr_txt", StringType)
    .add("supld_dspnsing_oac_pstl_cd_cd", StringType)
    .add("supld_dspnsd_rx_grp_id", StringType)
    .add("supld_dspnsd_rx_item_seq_nbr", IntegerType)
    .add("supld_rx_dspnsd_dt", IntegerType)
    .add("supld_rx_dspnsd_tm", IntegerType)
    .add("supld_pscrng_medpro_encrypt_id", StringType)
    .add("supld_dspnsing_sys_rec_typ_cd", StringType)
    .add("supld_dspnsd_rx_collected_ind", StringType)
    .add("supld_dspnsd_rx_pat_instr_txt", StringType)
    .add("supld_part_fill_rmng_unit_qty", StringType)
    .add("supld_nrsg_hm_ind", StringType)
    .add("supld_med_diag_cd_list_txt", StringType)
    .add("supld_reimbmnt_catg_cd", StringType)
    .add("supld_rx_typ_cd", StringType)
    .add("supld_rx_fill_typ_cd", IntegerType)
    .add("supld_rx_fill_st_cd", StringType)
    .add("supld_dspnsd_qty", StringType)
    .add("supld_pscr_qty", StringType)
    .add("supld_dspnsd_rx_item_uom_cd", StringType)
    .add("supld_dspnsd_rx_item_uom_txt", StringType)
    .add("supld_dspnsd_pip_id", StringType)
    .add("supld_pscr_pip_id", StringType)
    .add("supld_dspnsd_dmd_id", StringType)
    .add("supld_pscr_dmd_id", StringType)
    .add("supld_dspnsd_pmr1_id", StringType)
    .add("supld_pscr_pmr1_id", StringType)
    .add("supld_dspnsd_pmr2_id", StringType)
    .add("supld_pscr_pmr2_id", StringType)
    .add("supld_dspnsd_othr1_extrnl_id", StringType)
    .add("supld_pscr_othr1_extrnl_id", StringType)
    .add("supld_dspnsd_othr2_extrnl_id", StringType)
    .add("supld_pscr_othr2_extrnl_id", StringType)
    .add("supld_dspnsd_pcmdty_desc", StringType)
    .add("supld_pscr_pcmdty_desc", StringType)
    .add("supld_dspnsd_cmdty_prof_qty", StringType)
    .add("supld_pscr_cmdty_prof_qty", StringType)
    .add("supld_dspnsd_cmdty_strnt_txt", StringType)
    .add("supld_pscr_cmdty_strnt_txt", StringType)
    .add("supld_dspnsd_generic_pcmdty_ind", IntegerType)
    .add("supld_pscr_generic_pcmdty_ind", StringType)
    .add("supld_dspnsd_ean13_id", StringType)
    .add("supld_sllr_expc_pay_amt", StringType)
    .add("publ_eff_ts", TimestampType)
    .add("proc_nm", StringType)
    .add("src_sys_cre_ts", TimestampType)
    .add("src_sys_cre_by_nm", StringType)
    .add("src_sys_updt_ts", TimestampType)
    .add("src_sys_updt_by_nm", StringType)
    .add("src_sys_id", StringType)
    .add("src_sys_impl_id", StringType)
    .add("src_sys_oprtnl_stat_cd", StringType)
    .add("src_sys_oprtnl_stat_ts", TimestampType)
    .add("src_sys_btch_id", StringType)
    .add("oprtnl_stat_cd", ShortType)
    .add("btch_id", StringType)
    .add("cre_by_nm", StringType)
    .add("cre_ts", TimestampType)
    .add("trans_orig_typ_cd", ShortType)
    .add("trans_correct_id", StringType)
    .add("origl_trans_id", StringType)
    .add("dspnsing_oac_ref_impl_id", StringType)
    .add("dspnsing_oac_lgcy_ref_impl_id", StringType)
    .add("dspnsing_oac_brdgg_proc_ts", StringType)
    .add("dspnsing_oac_brdgg_accrcy_pct", DecimalType(5,2))
    .add("dspnsing_oac_brdgg_meth_nm", StringType)
    .add("dspnsing_oac_brdgg_stat_cd", StringType)
    .add("dspnsd_fcc_ref_impl_id", StringType)
    .add("dspnsd_fcc_brdgg_proc_ts", StringType)
    .add("dspnsd_fcc_brdgg_accrcy_pct", DecimalType(5,2))
    .add("dspnsd_fcc_brdgg_meth_nm", StringType)
    .add("dspnsd_fcc_brdgg_stat_cd", StringType)
    .add("pscr_fcc_ref_impl_id", StringType)
    .add("pscr_fcc_brdgg_proc_ts", StringType)
    .add("pscr_fcc_brdgg_accrcy_pct", DecimalType(5,2))
    .add("pscr_fcc_brdgg_meth_nm", StringType)
    .add("pscr_fcc_brdgg_stat_cd", StringType )
    .add("rx_dspnsd_tm_pd_id", IntegerType)
    .add("dervd_dsupp_proc_id", StringType)

  override lazy val createTableOpts =
    s"""
    STORED AS PARQUET
    TBLPROPERTIES ('parquet.compression'='SNAPPY')
  """

  def helperCreatePartitionSpec(rxDspnsdTmPdId: Int, dervdDsuppProcId: String): String = s"rx_dspnsd_tm_pd_id=CAST($rxDspnsdTmPdId as INT), dervd_dsupp_proc_id='${dervdDsuppProcId}'"

}
