package com.rxcorp.bdf.datalake.dk9.ndh.loadAsset.model.dwh.physical.shared

import com.rxcorp.bdf.datalake.dk9.ndh.loadAsset.common.AppContext
import com.rxcorp.bdf.datalake.dk9.ndh.loadAsset.common.model.Table
import org.apache.spark.sql.types._

abstract class AbstractGrrPcmdty(appContext: AppContext)  extends Table("") {

  override lazy val logicalName: String = "Provisioned Commodity Dimension"
  override lazy val physicalName: String = "v_grr_pcmdty_d"

  override lazy val tableColumns: Array[(String, String)] = Array(
    ("pcmdty_id", "BIGINT"),
    ("grr_pcmdty_cd", "DOUBLE"),
    ("fcc", "BIGINT"),
    ("pcmdty_cd", "DOUBLE"),
    ("pcmdty_desc", "STRING"),
    ("ctrysp_pcmdty_desc", "STRING"),
    ("form_desc", "STRING"),
    ("prod_abrv_txt", "STRING"),
    ("prod_cd", "DOUBLE"),
    ("pcmdty_lnch_dt", "STRING"),
    ("pcmdty_out_of_trade_dt", "STRING"),
    ("prod_lnch_dt", "STRING"),
    ("prod_out_of_trade_dt", "STRING"),
    ("atc1_cd", "STRING"),
    ("atc1_desc", "STRING"),
    ("atc2_cd", "STRING"),
    ("atc2_desc", "STRING"),
    ("atc3_cd", "STRING"),
    ("atc3_desc", "STRING"),
    ("atc4_cd", "STRING"),
    ("atc4_desc", "STRING"),
    ("atc4_short_desc", "STRING"),
    ("ctrysp_atc1_cd", "STRING"),
    ("ctrysp_atc1_desc", "STRING"),
    ("ctrysp_atc2_cd", "STRING"),
    ("ctrysp_atc2_desc", "STRING"),
    ("ctrysp_atc3_cd", "STRING"),
    ("ctrysp_atc3_desc", "STRING"),
    ("ctrysp_atc4_cd", "STRING"),
    ("ctrysp_atc4_desc", "STRING"),
    ("nfc1_cd", "STRING"),
    ("nfc1_desc", "STRING"),
    ("nfc2_cd", "STRING"),
    ("nfc2_desc", "STRING"),
    ("nfc12_cd", "STRING"),
    ("nfc12_desc", "STRING"),
    ("nfc23_cd", "STRING"),
    ("nfc23_desc", "STRING"),
    ("nfc123_cd", "STRING"),
    ("nfc123_desc", "STRING"),
    ("nfc3_cd", "STRING"),
    ("nfc3_desc", "STRING"),
    ("chc1_cd", "STRING"),
    ("chc1_desc", "STRING"),
    ("chc2_cd", "STRING"),
    ("chc2_desc", "STRING"),
    ("chc3_cd", "STRING"),
    ("chc3_desc", "STRING"),
    ("chc4_cd", "STRING"),
    ("chc4_desc", "STRING"),
    ("prod_form_cd", "STRING"),
    ("branded_prod_ind", "DOUBLE"),
    ("intl_prod_nm", "STRING"),
    ("pharmy_bnd_ind", "STRING"),
    ("hosp_mkt_sctr_ind", "DOUBLE"),
    ("med_mkt_sctr_ind", "DOUBLE"),
    ("cnsmr_hlth_mkt_sctr_ind", "DOUBLE"),
    ("pcmdty_size_cnt", "DOUBLE"),
    ("pcmdty_multr_fct", "DOUBLE"),
    ("ctrysp_pcmdty_cu_qty", "BIGINT"),
    ("rx_eqvlnc_cd", "BIGINT"),
    ("abs_strnt_qty", "BIGINT"),
    ("abs_strnt_uom_cd", "BIGINT"),
    ("rltv_strnt_qty", "BIGINT"),
    ("rltv_strnt_uom_cd", "STRING"),
    ("vol_qty", "BIGINT"),
    ("vol_uom_cd", "STRING"),
    ("protctn_stat_cd", "STRING"),
    ("protctn_stat_desc", "STRING"),
    ("est_protctn_expry_dt", "STRING"),
    ("lnch_stat_desc", "STRING"),
    ("intl_pcmdty_desc", "STRING"),
    ("intl_pcmdty_size_desc", "STRING"),
    ("intl_pcmdty_vol_desc", "STRING"),
    ("intl_pcmdty_strnt_desc", "STRING"),
    ("intl_pcmdty_form_desc", "STRING"),
    ("intl_prod_cd", "STRING"),
    ("intl_reimb_stat_desc", "STRING"),
    ("intl_rx_stat_cd", "STRING"),
    ("ctrysp_reimb_stat_cd", "STRING"),
    ("ctrysp_reimb_stat_desc", "STRING"),
    ("biol_ind_cd", "STRING"),
    ("biol_ind_desc", "STRING"),
    ("pcmdty_xfer_typ_cd", "STRING"),
    ("xfer_to_fcc", "DOUBLE"),
    ("pcmdty_xfer_dt", "STRING"),
    ("rptg_fcc", "DOUBLE"),
    ("pi_prod_ind_txt", "STRING"),
    ("logl_del_dt", "STRING"),
    ("pcmdty_eff_dt", "STRING"),
    ("pcmdty_expry_dt", "STRING"),
    ("isrt_dt", "STRING"),
    ("isrt_by_nm", "STRING"),
    ("last_updt_dt", "STRING"),
    ("last_updt_by_nm", "STRING"),
    ("cur_rec_ind", "DOUBLE"),
    ("pcmdty_wgt_qty", "BIGINT"),
    ("pcmdty_wgt_txt", "STRING"),
    ("pcmdty_vol_txt", "STRING"),
    ("pcmdty_strnt_txt", "STRING"),
    ("pcmdty_vol_or_wgt_txt", "STRING"),
    ("intl_generic_prod_clas_desc", "STRING"),
    ("ctrysp_pharmy_bnd_desc", "STRING"),
    ("pri_org_cd", "DOUBLE"),
    ("pri_org_lng_nm", "STRING"),
    ("pri_org_short_nm", "STRING"),
    ("ctrysp_pi_prod_stat_nm", "STRING"),
    ("pcmdty_substn_cnt", "DOUBLE"),
    ("ppk_desc", "STRING"),
    ("pcmdty_wgt_uom_cd", "STRING"),
    ("ctry_cd", "STRING"),
    ("ctry_desc", "STRING"),
    ("ctrysp_prod_nm_typ_nm", "STRING"),
    ("branded_prod_ind_txt", "STRING"),
    ("hosp_mkt_sctr_ind_txt", "STRING"),
    ("med_mkt_sctr_ind_txt", "STRING"),
    ("rx_bnd_pcmdty_ind", "STRING"),
    ("synd_otc_ind", "STRING"),
    ("chc1_cd_and_short_desc_txt", "STRING"),
    ("chc2_cd_and_short_desc_txt", "STRING"),
    ("chc3_cd_and_short_desc_txt", "STRING"),
    ("chc4_cd_and_short_desc_txt", "STRING"),
    ("atc1_cd_and_short_desc_txt", "STRING"),
    ("atc2_cd_and_short_desc_txt", "STRING"),
    ("atc3_cd_and_short_desc_txt", "STRING"),
    ("atc4_cd_and_short_desc_txt", "STRING"),
    ("nfc1_cd_and_short_desc_txt", "STRING"),
    ("nfc2_cd_and_short_desc_txt", "STRING"),
    ("nfc12_cd_and_short_desc_txt", "STRING"),
    ("nfc23_cd_and_short_desc_txt", "STRING"),
    ("nfc123_cd_and_short_desc_txt", "STRING"),
    ("pri_org_abrv_txt", "STRING"),
    ("ctrysp_rx_stat_desc", "STRING"),
    ("ctrysp_ppk_desc", "STRING"),
    ("pcmdty_prst_desc", "STRING"),
    ("ppk_prst_desc", "STRING"),
    ("clctr_rpter_rptg_fcc", "DOUBLE"),
    ("pri_pip_cd", "STRING"),
    ("pri_org_id", "DOUBLE"),
    ("ctry_id", "DOUBLE"),
    ("pbs_qty", "BIGINT"),
    ("pbs_uom_cd", "STRING"),
    ("pbs_fct", "BIGINT"),
    ("unlic_medcn_cd", "STRING"),
    ("unlic_medcn_short_desc", "STRING"),
    ("prod_nm_typ_desc", "STRING"),
    ("pharml_mkt_sctr_ind_txt", "STRING"),
    ("pharml_mkt_sctr_ind", "DOUBLE"),
    ("bus_eff_ts", "STRING"),
    ("bus_expry_ts", "STRING"),
    ("publ_eff_ts", "STRING"),
    ("publ_expry_ts", "STRING"),
    ("del_status_cd", "STRING")
  )



  override lazy val schema: StructType = (new StructType)
    .add("pcmdty_id", DoubleType)
    .add("grr_pcmdty_cd", DoubleType)
    .add("fcc", DoubleType)
    .add("pcmdty_cd", DoubleType)
    .add("pcmdty_desc", StringType)
    .add("ctrysp_pcmdty_desc", StringType)
    .add("form_desc", StringType)
    .add("prod_abrv_txt", StringType)
    .add("prod_cd", DoubleType)
    .add("pcmdty_lnch_dt", StringType)
    .add("pcmdty_out_of_trade_dt", StringType)
    .add("prod_lnch_dt", StringType)
    .add("prod_out_of_trade_dt", StringType)
    .add("atc1_cd", StringType)
    .add("atc1_desc", StringType)
    .add("atc2_cd", StringType)
    .add("atc2_desc", StringType)
    .add("atc3_cd", StringType)
    .add("atc3_desc", StringType)
    .add("atc4_cd", StringType)
    .add("atc4_desc", StringType)
    .add("atc4_short_desc", StringType)
    .add("ctrysp_atc1_cd", StringType)
    .add("ctrysp_atc1_desc", StringType)
    .add("ctrysp_atc2_cd", StringType)
    .add("ctrysp_atc2_desc", StringType)
    .add("ctrysp_atc3_cd", StringType)
    .add("ctrysp_atc3_desc", StringType)
    .add("ctrysp_atc4_cd", StringType)
    .add("ctrysp_atc4_desc", StringType)
    .add("nfc1_cd", StringType)
    .add("nfc1_desc", StringType)
    .add("nfc2_cd", StringType)
    .add("nfc2_desc", StringType)
    .add("nfc12_cd", StringType)
    .add("nfc12_desc", StringType)
    .add("nfc23_cd", StringType)
    .add("nfc23_desc", StringType)
    .add("nfc123_cd", StringType)
    .add("nfc123_desc", StringType)
    .add("nfc3_cd", StringType)
    .add("nfc3_desc", StringType)
    .add("chc1_cd", StringType)
    .add("chc1_desc", StringType)
    .add("chc2_cd", StringType)
    .add("chc2_desc", StringType)
    .add("chc3_cd", StringType)
    .add("chc3_desc", StringType)
    .add("chc4_cd", StringType)
    .add("chc4_desc", StringType)
    .add("prod_form_cd", StringType)
    .add("branded_prod_ind", DoubleType)
    .add("intl_prod_nm", StringType)
    .add("pharmy_bnd_ind", StringType)
    .add("hosp_mkt_sctr_ind", DoubleType)
    .add("med_mkt_sctr_ind", DoubleType)
    .add("cnsmr_hlth_mkt_sctr_ind", DoubleType)
    .add("pcmdty_size_cnt", DoubleType)
    .add("pcmdty_multr_fct", DoubleType)
    .add("ctrysp_pcmdty_cu_qty", LongType)
    .add("rx_eqvlnc_cd", LongType)
    .add("abs_strnt_qty", LongType)
    .add("abs_strnt_uom_cd", LongType)
    .add("rltv_strnt_qty", LongType)
    .add("rltv_strnt_uom_cd", StringType)
    .add("vol_qty", LongType)
    .add("vol_uom_cd", StringType)
    .add("protctn_stat_cd", StringType)
    .add("protctn_stat_desc", StringType)
    .add("est_protctn_expry_dt", StringType)
    .add("lnch_stat_desc", StringType)
    .add("intl_pcmdty_desc", StringType)
    .add("intl_pcmdty_size_desc", StringType)
    .add("intl_pcmdty_vol_desc", StringType)
    .add("intl_pcmdty_strnt_desc", StringType)
    .add("intl_pcmdty_form_desc", StringType)
    .add("intl_prod_cd", StringType)
    .add("intl_reimb_stat_desc", StringType)
    .add("intl_rx_stat_cd", StringType)
    .add("ctrysp_reimb_stat_cd", StringType)
    .add("ctrysp_reimb_stat_desc", StringType)
    .add("biol_ind_cd", StringType)
    .add("biol_ind_desc", StringType)
    .add("pcmdty_xfer_typ_cd", StringType)
    .add("xfer_to_fcc", DoubleType)
    .add("pcmdty_xfer_dt", StringType)
    .add("rptg_fcc", DoubleType)
    .add("pi_prod_ind_txt", StringType)
    .add("logl_del_dt", StringType)
    .add("pcmdty_eff_dt", StringType)
    .add("pcmdty_expry_dt", StringType)
    .add("isrt_dt", StringType)
    .add("isrt_by_nm", StringType)
    .add("last_updt_dt", StringType)
    .add("last_updt_by_nm", StringType)
    .add("cur_rec_ind", DoubleType)
    .add("pcmdty_wgt_qty", LongType)
    .add("pcmdty_wgt_txt", StringType)
    .add("pcmdty_vol_txt", StringType)
    .add("pcmdty_strnt_txt", StringType)
    .add("pcmdty_vol_or_wgt_txt", StringType)
    .add("intl_generic_prod_clas_desc", StringType)
    .add("ctrysp_pharmy_bnd_desc", StringType)
    .add("pri_org_cd", DoubleType)
    .add("pri_org_lng_nm", StringType)
    .add("pri_org_short_nm", StringType)
    .add("ctrysp_pi_prod_stat_nm", StringType)
    .add("pcmdty_substn_cnt", DoubleType)
    .add("ppk_desc", StringType)
    .add("pcmdty_wgt_uom_cd", StringType)
    .add("ctry_cd", StringType)
    .add("ctry_desc", StringType)
    .add("ctrysp_prod_nm_typ_nm", StringType)
    .add("branded_prod_ind_txt", StringType)
    .add("hosp_mkt_sctr_ind_txt", StringType)
    .add("med_mkt_sctr_ind_txt", StringType)
    .add("rx_bnd_pcmdty_ind", StringType)
    .add("synd_otc_ind", StringType)
    .add("chc1_cd_and_short_desc_txt", StringType)
    .add("chc2_cd_and_short_desc_txt", StringType)
    .add("chc3_cd_and_short_desc_txt", StringType)
    .add("chc4_cd_and_short_desc_txt", StringType)
    .add("atc1_cd_and_short_desc_txt", StringType)
    .add("atc2_cd_and_short_desc_txt", StringType)
    .add("atc3_cd_and_short_desc_txt", StringType)
    .add("atc4_cd_and_short_desc_txt", StringType)
    .add("nfc1_cd_and_short_desc_txt", StringType)
    .add("nfc2_cd_and_short_desc_txt", StringType)
    .add("nfc12_cd_and_short_desc_txt", StringType)
    .add("nfc23_cd_and_short_desc_txt", StringType)
    .add("nfc123_cd_and_short_desc_txt", StringType)
    .add("pri_org_abrv_txt", StringType)
    .add("ctrysp_rx_stat_desc", StringType)
    .add("ctrysp_ppk_desc", StringType)
    .add("pcmdty_prst_desc", StringType)
    .add("ppk_prst_desc", StringType)
    .add("clctr_rpter_rptg_fcc", DoubleType)
    .add("pri_pip_cd", StringType)
    .add("pri_org_id", DoubleType)
    .add("ctry_id", DoubleType)
    .add("pbs_qty", LongType)
    .add("pbs_uom_cd", StringType)
    .add("pbs_fct", LongType)
    .add("unlic_medcn_cd", StringType)
    .add("unlic_medcn_short_desc", StringType)
    .add("prod_nm_typ_desc", StringType)
    .add("pharml_mkt_sctr_ind_txt", StringType)
    .add("pharml_mkt_sctr_ind", DoubleType)
    .add("bus_eff_ts", StringType)
    .add("bus_expry_ts", StringType)
    .add("publ_eff_ts", StringType)
    .add("publ_expry_ts", StringType)
    .add("del_status_cd", StringType)


  override lazy val createTableOpts: String =
    """
      |  STORED AS PARQUET
      |  TBLPROPERTIES ('parquet.compression'='SNAPPY')
    """.stripMargin


}
