package com.rxcorp.bdf.datalake.dk9.ndh.loadAsset.model.dwh.physical.shared

import com.rxcorp.bdf.datalake.dk9.ndh.loadAsset.common.AppContext
import com.rxcorp.bdf.datalake.dk9.ndh.loadAsset.common.model.Table
import org.apache.spark.sql.types._

abstract class AbstractTimeDyDim(appContext: AppContext) extends Table("") {

  override lazy val logicalName: String = "Time Day Dimension"
  override lazy val physicalName: String = "v_tm_pd_gre_day_dim"

  override lazy val tableColumns = Array(
    ("tm_pd_id", "int"),
    ("publ_eff_ts", "timestamp"),
    ("bus_eff_dt", "timestamp"),
    ("day_strt_dt", "string"),
    ("day_end_dt", "string"),
    ("day_shrt_nm", "string"),
    ("day_nm", "string"),
    ("day_nbr", "int"),
    ("wk_mon_strt_tm_pd_id", "int"),
    ("wk_mon_strt_dt", "string"),
    ("wk_mon_end_dt", "string"),
    ("wk_tue_strt_tm_pd_id", "int"),
    ("wk_tue_strt_dt", "string"),
    ("wk_tue_end_dt", "string"),
    ("wk_wed_strt_tm_pd_id", "int"),
    ("wk_wed_strt_dt", "string"),
    ("wk_wed_end_dt", "string"),
    ("wk_thu_strt_tm_pd_id", "int"),
    ("wk_thu_strt_dt", "string"),
    ("wk_thu_end_dt", "string"),
    ("wk_fri_strt_tm_pd_id", "int"),
    ("wk_fri_strt_dt", "string"),
    ("wk_fri_end_dt", "string"),
    ("wk_sat_strt_tm_pd_id", "int"),
    ("wk_sat_strt_dt", "string"),
    ("wk_sat_end_dt", "string"),
    ("wk_sun_strt_tm_pd_id", "int"),
    ("wk_sun_end_dt", "string"),
    ("wk_sun_strt_dt", "string"),
    ("mth_tm_pd_id", "int"),
    ("mth_strt_dt", "string"),
    ("mth_end_dt", "string"),
    ("mth_shrt_nm", "string"),
    ("mth_nm", "string"),
    ("day_in_mth_nbr", "int"),
    ("qtr_tm_pd_id", "int"),
    ("qtr_strt_dt", "string"),
    ("qtr_end_dt", "string"),
    ("qtr_shrt_nm", "string"),
    ("qtr_nm", "string"),
    ("day_in_qtr_nbr", "int"),
    ("half_yr_tm_pd_id", "int"),
    ("half_yr_strt_dt", "string"),
    ("half_yr_end_dt", "string"),
    ("half_yr_shrt_nm", "string"),
    ("half_yr_nm", "string"),
    ("day_in_half_yr_nbr", "int"),
    ("yr_tm_pd_id", "int"),
    ("yr_strt_dt", "string"),
    ("yr_end_dt", "string"),
    ("yr_shrt_nm", "string"),
    ("yr_nm", "string"),
    ("day_in_yr_nbr", "int"),
    ("publ_expry_ts", "string"),
    ("bus_expry_dt", "string"),
    ("mth_nbr", "int"),
    ("qtr_nbr", "int"),
    ("half_yr_nbr", "int"),
    ("yr_nbr", "int"),
    ("wk_mon_strt_shrt_nm", "string"),
    ("wk_mon_strt_nm", "string"),
    ("wk_mon_strt_nbr", "int"),
    ("day_in_wk_mon_strt_nbr", "int"),
    ("wk_tue_strt_shrt_nm", "string"),
    ("wk_tue_strt_nm", "string"),
    ("wk_tue_strt_nbr", "int"),
    ("day_in_wk_tue_strt_nbr", "int"),
    ("wk_wed_strt_shrt_nm", "string"),
    ("wk_wed_strt_nm", "string"),
    ("wk_wed_strt_nbr", "int"),
    ("day_in_wk_wed_strt_nbr", "int"),
    ("wk_thu_strt_shrt_nm", "string"),
    ("wk_thu_strt_nm", "string"),
    ("wk_thu_strt_nbr", "int"),
    ("day_in_wk_thu_strt_nbr", "int"),
    ("wk_fri_strt_shrt_nm", "string"),
    ("wk_fri_strt_nm", "string"),
    ("wk_fri_strt_nbr", "int"),
    ("day_in_wk_fri_strt_nbr", "int"),
    ("wk_sat_strt_shrt_nm", "string"),
    ("wk_sat_strt_nm", "string"),
    ("wk_sat_strt_nbr", "int"),
    ("day_in_wk_sat_strt_nbr", "int"),
    ("wk_sun_strt_shrt_nm", "string"),
    ("wk_sun_strt_nm", "string"),
    ("wk_sun_strt_nbr", "int"),
    ("day_in_wk_sun_strt_nbr", "int")
  )

  override lazy val schema = StructType(Array(
    StructField("tm_pd_id", IntegerType, true),
    StructField("publ_eff_ts", TimestampType, true),
    StructField("bus_eff_dt", TimestampType, true),
    StructField("day_strt_dt", StringType, true),
    StructField("day_end_dt", StringType, true),
    StructField("day_shrt_nm", StringType, true),
    StructField("day_nm", StringType, true),
    StructField("day_nbr", IntegerType, true),
    StructField("wk_mon_strt_tm_pd_id", IntegerType, true),
    StructField("wk_mon_strt_dt", StringType, true),
    StructField("wk_mon_end_dt", StringType, true),
    StructField("wk_tue_strt_tm_pd_id", IntegerType, true),
    StructField("wk_tue_strt_dt", StringType, true),
    StructField("wk_tue_end_dt", StringType, true),
    StructField("wk_wed_strt_tm_pd_id", IntegerType, true),
    StructField("wk_wed_strt_dt", StringType, true),
    StructField("wk_wed_end_dt", StringType, true),
    StructField("wk_thu_strt_tm_pd_id", IntegerType, true),
    StructField("wk_thu_strt_dt", StringType, true),
    StructField("wk_thu_end_dt", StringType, true),
    StructField("wk_fri_strt_tm_pd_id", IntegerType, true),
    StructField("wk_fri_strt_dt", StringType, true),
    StructField("wk_fri_end_dt", StringType, true),
    StructField("wk_sat_strt_tm_pd_id", IntegerType, true),
    StructField("wk_sat_strt_dt", StringType, true),
    StructField("wk_sat_end_dt", StringType, true),
    StructField("wk_sun_strt_tm_pd_id", IntegerType, true),
    StructField("wk_sun_end_dt", StringType, true),
    StructField("wk_sun_strt_dt", StringType, true),
    StructField("mth_tm_pd_id", IntegerType, true),
    StructField("mth_strt_dt", StringType, true),
    StructField("mth_end_dt", StringType, true),
    StructField("mth_shrt_nm", StringType, true),
    StructField("mth_nm", StringType, true),
    StructField("day_in_mth_nbr", IntegerType, true),
    StructField("qtr_tm_pd_id", IntegerType, true),
    StructField("qtr_strt_dt", StringType, true),
    StructField("qtr_end_dt", StringType, true),
    StructField("qtr_shrt_nm", StringType, true),
    StructField("qtr_nm", StringType, true),
    StructField("day_in_qtr_nbr", IntegerType, true),
    StructField("half_yr_tm_pd_id", IntegerType, true),
    StructField("half_yr_strt_dt", StringType, true),
    StructField("half_yr_end_dt", StringType, true),
    StructField("half_yr_shrt_nm", StringType, true),
    StructField("half_yr_nm", StringType, true),
    StructField("day_in_half_yr_nbr", IntegerType, true),
    StructField("yr_tm_pd_id", IntegerType, true),
    StructField("yr_strt_dt", StringType, true),
    StructField("yr_end_dt", StringType, true),
    StructField("yr_shrt_nm", StringType, true),
    StructField("yr_nm", StringType, true),
    StructField("day_in_yr_nbr", IntegerType, true),
    StructField("publ_expry_ts", StringType, true),
    StructField("bus_expry_dt", StringType, true),
    StructField("mth_nbr", IntegerType, true),
    StructField("qtr_nbr", IntegerType, true),
    StructField("half_yr_nbr", IntegerType, true),
    StructField("yr_nbr", IntegerType, true),
    StructField("wk_mon_strt_shrt_nm", StringType, true),
    StructField("wk_mon_strt_nm", StringType, true),
    StructField("wk_mon_strt_nbr", IntegerType, true),
    StructField("day_in_wk_mon_strt_nbr", IntegerType, true),
    StructField("wk_tue_strt_shrt_nm", StringType, true),
    StructField("wk_tue_strt_nm", StringType, true),
    StructField("wk_tue_strt_nbr", IntegerType, true),
    StructField("day_in_wk_tue_strt_nbr", IntegerType, true),
    StructField("wk_wed_strt_shrt_nm", StringType, true),
    StructField("wk_wed_strt_nm", StringType, true),
    StructField("wk_wed_strt_nbr", IntegerType, true),
    StructField("day_in_wk_wed_strt_nbr", IntegerType, true),
    StructField("wk_thu_strt_shrt_nm", StringType, true),
    StructField("wk_thu_strt_nm", StringType, true),
    StructField("wk_thu_strt_nbr", IntegerType, true),
    StructField("day_in_wk_thu_strt_nbr", IntegerType, true),
    StructField("wk_fri_strt_shrt_nm", StringType, true),
    StructField("wk_fri_strt_nm", StringType, true),
    StructField("wk_fri_strt_nbr", IntegerType, true),
    StructField("day_in_wk_fri_strt_nbr", IntegerType, true),
    StructField("wk_sat_strt_shrt_nm", StringType, true),
    StructField("wk_sat_strt_nm", StringType, true),
    StructField("wk_sat_strt_nbr", IntegerType, true),
    StructField("day_in_wk_sat_strt_nbr", IntegerType, true),
    StructField("wk_sun_strt_shrt_nm", StringType, true),
    StructField("wk_sun_strt_nm", StringType, true),
    StructField("wk_sun_strt_nbr", IntegerType, true),
    StructField("day_in_wk_sun_strt_nbr", IntegerType, true)
  ))

  override lazy val createTableOpts =
    s"""
    STORED AS PARQUET
    TBLPROPERTIES ('parquet.compression'='SNAPPY')
  """
}
